### ISSUE TITLE
[Combat] Create option to hide non-relevant stages of the Grayscales. 

### ISSUE THREAD

**Issue by LeeRhodes** [LeeRhodes/roll20-character-sheets#2]
After making the improvement of adding the new grey scale rows, find a way to hide them when a character doesn't have need of them. (probably just toggle buttons)

**Comment by Seraaron** [comment]
If possible, I think that the only thing needed for this is a drop-down menu for every point on the current form of the PTGS. In the same way that we already have for changing the wound type (Bu/Su/Li/Mi/Se/Tr/M), we could have one for shade too (B/G/W). That way it takes up less visual space and is still quite clear and easy to use. It doesn't even really need any logical functions tied to it, the mechanical aspects are already handled by wound type. The shade is just for visual reference. 

On top of that, I don't think it's even mathematically possible for a creature to have a health bar that spans all the way from Black to White (just based on the way the spacing of the PTGS is calculated), so overlap would almost never be an issue.

**Comment by LeeRhodes** [comment]
I agree this would be relevant really only for a couple characters and monsters, but I think it should be an option in any case. I know for one of they characters it was super handy (they had gray MW). Aimed mostly been a GM aid, but will likely fold this into a monster burner option. Closing this :)
