### ISSUE TITLE
[Character Sheet] Limited number of recordable skill tests

### ISSUE THREAD

**Issue by OwenBrush** [LeeRhodes/roll20-character-sheets#7]
The limit of 4 skill tests for routine and difficult tests prevents routine tests for greed and hatred from being properly recorded (they are an exception to the rule and continue counting routine tests even after exponent 4)

It also prevents the 5th difficult test that is needed to advance to exponent 10 in any skill or attribute from being recorded.

And, aesthetically, the limit of 3 challenging tests, with the last bubble being already filled in, is confusing - as it can appear that there is a free test granted.

Thanks for taking this on!

**Comment by LeeRhodes** [comment]
Way I am thinking of implementing this is adding an option to tick the stat as an emotional attribute where it will continue calculating points needed. 

Simple enough to add a fifth bubble for difficult. 

Agree the already marked challenging bubble needs to go.

**Comment by LeeRhodes** [comment]
<img width="771" alt="screen shot 2018-06-15 at 16 08 00" src="https://user-images.githubusercontent.com/19798820/41475309-5988eef0-70b6-11e8-8180-0a9c1cb986db.png">

Fixed the limit and removed the challenging icon.

I will have a look into the routine marking for emotional stats.

**Comment by LeeRhodes** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/3835

**Comment by Seraaron** [comment]
Really glad you added the fifth bubbles for all abilities. It looks so much nicer, and makes customised skill progression options a lot easier for house-ruling GMs like myself to handle.

**Comment by LeeRhodes** [comment]
Was close. Has been merged into main sheets on roll20.
